# Generated by Django 4.2.1 on 2023-05-13 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vencimientos.agency')),
            ],
        ),
        migrations.CreateModel(
            name='DueDateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField()),
                ('day', models.SmallIntegerField()),
                ('next_month', models.BooleanField(default=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vencimientos.criteria')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vencimientos.tax')),
            ],
        ),
        migrations.CreateModel(
            name='DueDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('value', models.SmallIntegerField()),
                ('due_date', models.DateField()),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vencimientos.criteria')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vencimientos.tax')),
            ],
        ),
    ]
