# Generated by Django 4.2.1 on 2023-05-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vencimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name_plural': 'taxes'},
        ),
        migrations.AlterUniqueTogether(
            name='tax',
            unique_together={('agency', 'name')},
        ),
    ]
