# Generated by Django 4.2.1 on 2023-05-24 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vencimientos", "0002_alter_tax_options_alter_tax_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("cuit", models.CharField(max_length=11)),
            ],
            options={
                "verbose_name_plural": "companies",
            },
        ),
        migrations.AlterModelOptions(
            name="agency",
            options={"verbose_name_plural": "agencies"},
        ),
        migrations.CreateModel(
            name="CompaniesDueDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vencimientos.company",
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vencimientos.tax",
                    ),
                ),
            ],
        ),
    ]
