# Generated by Django 4.2.1 on 2023-05-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vencimientos", "0003_company_alter_agency_options_companiesduedate"),
    ]

    operations = [
        migrations.AddField(
            model_name="tax",
            name="periodicidad",
            field=models.CharField(
                choices=[
                    ("A", "Anual"),
                    ("M", "Mensual"),
                    ("B", "Bimestral"),
                    ("T", "Trimestral"),
                    ("C", "Cuatrimestral"),
                ],
                default="M",
                max_length=1,
            ),
        ),
    ]
